### ISSUE TITLE
Error loading config file: unknown field "dynamic_substitutions" in cloudbuild.BuildOptions

### ISSUE THREAD

**Issue by kwladyka** [GoogleCloudPlatform/cloud-build-local#118]
`cloud-build-local` is not compatible with `gcloud builds`. The issue is `dynamic_substitutions`.

Here is doc about `dynamic_substitutions`:
https://cloud.google.com/cloud-build/docs/configuring-builds/use-bash-and-bindings-in-substitutions

**reproduce the issue:**

cloudbuild.yaml
```yaml
options:
  dynamic_substitutions: true
substitutions:
  _IMAGE_TAG: '${TAG_NAME:-latest}'
  _IMAGE: 'eu.gcr.io/${PROJECT_ID}/${REPO_NAME}:${_IMAGE_TAG}'
  _REVISION_SUFFIX_TAG: '${TAG_NAME//./-}'
  _REVISION_SUFFIX: '${_REVISION_SUFFIX_TAG:-${SHORT_SHA}}'
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo _IMAGE_TAG $_IMAGE_TAG, _IMAGE $_IMAGE, _REVISION_SUFFIX_TAG $_REVISION_SUFFIX_TAG, _REVISION_SUFFIX $_REVISION_SUFFIX'
      - 'echo TAG_NAME $TAG_NAME, SHORT_SHA $SHORT_SHA, REPO_NAME $REPO_NAME'
```

run build locally and experience the issue:
```bash
cloud-build-local --substitutions=REPO_NAME=foo,SHORT_SHA=1234,TAG_NAME=v1.2.3 --dryrun=false .
2020/07/18 18:45:36 Error loading config file: unknown field "dynamic_substitutions" in cloudbuild.BuildOptions
```

expected result:
```bash
gcloud builds submit --no-source --substitutions=REPO_NAME=foo,SHORT_SHA=1234,TAG_NAME=v1.2.3 --config=cloudbuild.yaml
_IMAGE_TAG v1.2.3, _IMAGE eu.gcr.io/staging-redjar/foo:v1.2.3, _REVISION_SUFFIX_TAG v1-2-3, _REVISION_SUFFIX v1-2-3
```

---

PS There is also a bug in `glcoud builds`:
`- 'echo TAG_NAME $TAG_NAME, SHORT_SHA $SHORT_SHA, REPO_NAME $REPO_NAME'`

this line has to be added while it is useless because of
```
ERROR: (gcloud.builds.submit) INVALID_ARGUMENT: invalid build: key "REPO_NAME" in the substitution data is not matched in the template;key "SHORT_SHA" in the substitution data is not matched in the template;key "TAG_NAME" in the substitution data is not matched in the template
```
which is not true, because this variables are used in `substitutions`. But not in `steps`. Not sure if this needs to be fixed in `cloud-build-local` separately from `gcloud builds` or report for `gclod builds` is enough.

I created the issue here for `gcloud builds`:
https://issuetracker.google.com/issues/161588167
