### ISSUE TITLE
Error response from daemon: error while removing network: network cloudbuild id XXX has active endpoints

### ISSUE THREAD

**Issue by Emixam23-FCMS** [GoogleCloudPlatform/cloud-build-local#121]
Hi,

I am having "a kind of an issue" where, for some integration tests, I need to run as a step a docker-compose up (which runs/launch two databases -> postgres & oracle).

> Output
```
DONE
Error response from daemon: error while removing network: network cloudbuild id 20a939ac64d84fa538772d6f5af954ccb73f606f5a738b9187e19b9ce13e6ee7 has active endpoints
```

Any idea about how to stop the containers? I don't think it's quite possible from witihn docker-compose itself, but what about from cloud build itself? Thanks

--------------------

**test.integration.docker-compose.yml**
```
version: "3.7"

services:
  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=**********
      - POSTGRES_PASSWORD=**********
      - POSTGRES_DB=**********
    network_mode: cloudbuild
  oracle:
    image: chameleon82/oracle-xe-10g
    container_name: oracle
    network_mode: cloudbuild

networks:
  default:
    external:
      name: cloudbuild
```

**test.integration.yaml**
```
steps:

  # Runs/Launch databases
  - name: 'docker/compose'
    args: [
        '-f',
        'deployments/cloud-build/test.integration.docker-compose.yml',
        'up',
        '--build',
        '-d'
    ]
    id: 'databases-docker-compose'

  # Runs tests
  - name: golang:1.15
    entrypoint: '/bin/bash'
    volumes:
      - name: "usr"
        path: "/usr"
    env:
      - "XXX=YYY"
    args:
      - '-c'
      - '.........'
```

Thanks for any hints/help :+1:
