### ISSUE TITLE
docker-compose: containers are left running

### ISSUE THREAD

**Issue by mbana** [GoogleCloudPlatform/cloud-build-local#77]
With a setup like below, `docker ps` or `docker-compose ps` shows that the containers are still running on my local machine. This happens I think both on failure and success.

```sh
$  cloud-build-local --config=cloudbuild.yaml --dryrun=false .
...
$ docker ps
$ docker-compose ps
```

**cloudbuild.yaml:**

```yaml
steps:
- name: 'docker/compose:1.15.0'
  args: ['up', '-d','redis', 'mongo']

- name: 'alpine'
  args: ['sh', '-c', 'while ! nc -v -z localhost 27017; do echo -e "\033[92m  ---> waiting for mongo ... \033[0m"; sleep 1; done']
```

**docker-compose.yml:**

```yaml
version: "3"
services:
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    # networks:
    #   - some_network
    ports:
      - 6379:6379

  mongo:
    image: mongo:3.6-jessie
    container_name: mongo
    hostname: mongo
    # networks:
    #   - some_network
    ports:
      - 27017:27017

# networks:
#   some_network:
```
